from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT_PATH = REPO_ROOT / "data" / "processed" / "t27_repo_reusability_inventory.json"

ALLOWED_CATEGORIES = {
    "core_reusable",
    "project_specific",
    "historical_campaign_tooling",
    "debug_or_diagnostic",
    "runtime_contract",
    "accepted_project_artifact",
    "candidate_for_archive",
    "candidate_for_project_repo",
}


def item(
    path: str,
    *,
    type: str,
    category: str,
    runtime_critical: bool,
    reusable: bool,
    project_specific: bool,
    recommended_action: str,
    notes: str,
) -> dict[str, object]:
    if category not in ALLOWED_CATEGORIES:
        raise ValueError(f"Unsupported category for {path}: {category}")
    return {
        "path": path,
        "type": type,
        "category": category,
        "runtime_critical": runtime_critical,
        "reusable": reusable,
        "project_specific": project_specific,
        "recommended_action": recommended_action,
        "notes": notes,
    }


def build_inventory() -> list[dict[str, object]]:
    inventory = [
        item(
            "README.md",
            type="file",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_primary_repo_overview",
            notes="Top-level explanation of the repository as a reusable runtime and framework.",
        ),
        item(
            "artifact_contracts.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_runtime_contract_source",
            notes="Defines active runtime paths, operational contracts, script classifications, and onboarding profiles.",
        ),
        item(
            "run_operational_pipeline.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_stable_operational_entrypoint",
            notes="Stable operational build entrypoint for the current runtime pipeline.",
        ),
        item(
            "run_runtime_clean_rebuild.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_stable_clean_rebuild_entrypoint",
            notes="Stable clean rebuild wrapper for accepted manuals in the reusable runtime path.",
        ),
        item(
            "query_workbench.py",
            type="file",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_runtime_consumer_utility",
            notes="Manual query utility over the operational runtime; useful beyond the current project corpus.",
        ),
        item(
            "check_mistral_api_usage.py",
            type="file",
            category="debug_or_diagnostic",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_diagnostic_utility",
            notes="Provider smoke-test script for API availability and rate-limit diagnostics, not part of the runtime path.",
        ),
        item(
            "run_t25_sequential_integration.py",
            type="file",
            category="historical_campaign_tooling",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_but_declassify_from_operational_path",
            notes="Campaign-specific wrapper for T25 onboarding work; should remain traceability only.",
        ),
        item(
            "run_t25_2_installation_recovery.py",
            type="file",
            category="historical_campaign_tooling",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_but_declassify_from_operational_path",
            notes="Task-specific installation recovery wrapper, useful only as historical recovery traceability.",
        ),
        item(
            "run_t26_error_manual_onboarding.py",
            type="file",
            category="historical_campaign_tooling",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_but_declassify_from_operational_path",
            notes="Campaign wrapper for the error manual onboarding flow; not an official runtime entrypoint.",
        ),
        item(
            "requirements.txt",
            type="file",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_environment_contract",
            notes="Shared dependency declaration for the runtime and supporting utilities.",
        ),
        item(
            "cache/terms_cache.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_and_rebuild_from_project_corpus",
            notes="Shared terminology cache currently derived from the accepted project manuals rather than a generic corpus.",
        ),
        item(
            "codes_endika/",
            type="directory",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="archive_as_legacy_research_material",
            notes="Legacy pre-runtime experiments and scripts outside the current operational architecture.",
        ),
        item(
            "docs/README.md",
            type="file",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_and_align_with_runtime_contract",
            notes="Documentation index for the reusable repository and its operational guidance.",
        ),
        item(
            "docs/operational_pipeline_runbook.md",
            type="file",
            category="runtime_contract",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_runbook",
            notes="Runbook for rebuild, validation, and operational handling of the live runtime.",
        ),
        item(
            "docs/operational_artifact_contract.md",
            type="file",
            category="runtime_contract",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_runtime_artifact_reference",
            notes="Explains the active operational artifact contract consumed by the runtime.",
        ),
        item(
            "docs/runtime_clean_rebuild_plan.md",
            type="file",
            category="historical_campaign_tooling",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_transition_planning_document",
            notes="Planning artifact for the clean rebuild effort; useful context but not part of the stable runtime contract.",
        ),
        item(
            "misc/coding-team/repo-reusability-core-split/",
            type="directory",
            category="historical_campaign_tooling",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_architect_planning_traceability",
            notes="Approved architect briefs and planning artifacts for T27 work; not operational runtime assets.",
        ),
        item(
            "src/1_ingestion/",
            type="directory",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_ingestion_layer",
            notes="Reusable ingestion layer for term loading, language utilities, and density analysis.",
        ),
        item(
            "src/1_ingestion/density_analyzer.py",
            type="file",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_ingestion_stage",
            notes="Reusable density analysis stage used before operational A-Box input generation.",
        ),
        item(
            "src/1_ingestion/termLoader.py",
            type="file",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_term_cache_builder",
            notes="General term cache builder even though the current cache content is project-specific.",
        ),
        item(
            "src/2_extraction/",
            type="directory",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_legacy_experimental_track",
            notes="Legacy experimental T-Box extraction path, outside the current operational runtime.",
        ),
        item(
            "src/3_merging/",
            type="directory",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_legacy_experimental_track",
            notes="Legacy experimental graph merging path replaced by the operational A-Box pipeline.",
        ),
        item(
            "src/5_alignment/",
            type="directory",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_legacy_experimental_track",
            notes="Legacy semantic reduction experiments that are not part of the live runtime contract.",
        ),
        item(
            "src/6_extraction/",
            type="directory",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_core_runtime_build_layer",
            notes="Operational A-Box build chain used by the live runtime and clean rebuild path.",
        ),
        item(
            "src/6_extraction/abox_input_builder.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Transforms density outputs into the structured A-Box extraction input payload.",
        ),
        item(
            "src/6_extraction/abox_extractor.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Main A-Box LLM extraction stage with retry profiles and model-fallback logic.",
        ),
        item(
            "src/6_extraction/abox_merger.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Operational raw graph merge stage for freshly extracted A-Box fragments.",
        ),
        item(
            "src/6_extraction/abox_canonicalizer.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Canonicalization stage that materializes entity merges before runtime publication.",
        ),
        item(
            "src/6_extraction/abox_graph_enricher.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Operational graph enrichment stage over the canonical A-Box.",
        ),
        item(
            "src/6_extraction/abox_link_completer.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Final link-completion stage that produces the published operational A-Box.",
        ),
        item(
            "src/6_extraction/abox_resume_policy.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_support_module",
            notes="Controls manifest reuse and compatible-output checks during operational extraction.",
        ),
        item(
            "src/6_extraction/canonical_resolution_policy.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_policy_module",
            notes="Defines canonicalization policy used by the live runtime build chain.",
        ),
        item(
            "src/6_extraction/enrichment_policy.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_policy_module",
            notes="Enrichment policy module for the current runtime build chain.",
        ),
        item(
            "src/6_extraction/link_completion_policy.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_policy_module",
            notes="Link-completion policy module for the current runtime build chain.",
        ),
        item(
            "src/7_database/",
            type="directory",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_runtime_backend_layer",
            notes="Reusable GraphDB and local store integration layer for runtime publication and consumption.",
        ),
        item(
            "src/7_database/publish_to_graphdb.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_official_publish_entrypoint",
            notes="Official GraphDB publication entrypoint for the active runtime.",
        ),
        item(
            "src/7_database/graphdb_healthcheck.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_official_healthcheck_entrypoint",
            notes="Official GraphDB healthcheck entrypoint for the active runtime mirror.",
        ),
        item(
            "src/7_database/graph_store.py",
            type="file",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_backend_abstraction",
            notes="Backend abstraction between local RDFLib usage and GraphDB remote usage.",
        ),
        item(
            "src/8_retrieval/",
            type="directory",
            category="core_reusable",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_but_document_domain_couplings",
            notes="Retrieval layer is reusable overall, but specific planners and anchors include project-coupled logic that should be made explicit.",
        ),
        item(
            "src/8_retrieval/text_to_sparql.py",
            type="file",
            category="project_specific",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="split_generic_planner_core_from_project_catalogs_later",
            notes="Core planner mechanics are reusable, but current plan families and anchors are strongly tied to the accepted broaching/CNC project scope.",
        ),
        item(
            "src/8_retrieval/multilingual_query_normalizer.py",
            type="file",
            category="project_specific",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="reclassify_as_project_config_heavy_module",
            notes="General normalization exists, but current anchor groups and collision rules are coupled to the current manual corpus.",
        ),
        item(
            "src/8_retrieval/synthesis_pipeline.py",
            type="file",
            category="project_specific",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="retain_with_explicit_project_tuning_boundary",
            notes="Reusable synthesis scaffolding exists, but answer-shaping rules are tuned against current project QA expectations.",
        ),
        item(
            "src/8_retrieval/multilingual_lexicon_builder.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_operational_stage",
            notes="Official lexicon build stage in the stable runtime rebuild contract.",
        ),
        item(
            "src/8_retrieval/qa_evaluator.py",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_official_evaluation_entrypoint",
            notes="Runtime evaluation entrypoint reused across the current baseline and accepted manual-specific QA datasets.",
        ),
        item(
            "src/8_retrieval/qa_sandbox_diagnostic.py",
            type="file",
            category="debug_or_diagnostic",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_diagnostic_tool",
            notes="Sandbox-specific QA diagnostics, not part of the main operational contract.",
        ),
        item(
            "src/9_rag_orchestrator/",
            type="directory",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_reusable_orchestration_layer",
            notes="RAG orchestration layer sits on top of the runtime and is not inherently bound to the current machine family.",
        ),
        item(
            "tests/",
            type="directory",
            category="core_reusable",
            runtime_critical=False,
            reusable=True,
            project_specific=False,
            recommended_action="retain_and_expand_gradually",
            notes="Test package placeholder for reusable validation growth; current project uses command-based validation heavily.",
        ),
        item(
            "data/raw/",
            type="directory",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="treat_as_project_input_space",
            notes="Manual source corpus belongs to the current industrial project and should move with the future case-specific repository.",
        ),
        item(
            "data/raw/chunks_manual_instrucciones_a218.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_project_source_manual",
            notes="Accepted source manual feeding the current runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_8070_quick_ref.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_project_source_manual",
            notes="Accepted quick-reference source manual feeding the current runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_8070_installation_manual.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_project_source_manual",
            notes="Accepted installation source manual feeding the current runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_man_8070_err.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_project_source_manual",
            notes="Accepted error manual feeding the current runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_8070_operating_programming_manual.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_candidate",
            notes="Project-specific source manual not yet in the accepted runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_8070_programming_manual.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_candidate",
            notes="Project-specific source manual not yet in the accepted runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_8070_remote_modules.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_candidate",
            notes="Project-specific source manual not yet in the accepted runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_manual_variables_cnc_8070.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_candidate",
            notes="Project-specific source manual not yet in the accepted runtime rebuild scope.",
        ),
        item(
            "data/raw/chunks_dds_soft.txt",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_candidate",
            notes="Project-specific source manual not yet in the accepted runtime rebuild scope.",
        ),
        item(
            "data/raw/density_report.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="retain_but_reclassify_as_legacy_default_density_input",
            notes="Legacy default density report for the A218-only path; should not be treated as the sole truth source of a clean multi-manual rebuild.",
        ),
        item(
            "data/raw/Chunks/1000/",
            type="directory",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="archive_or_document_as_legacy_chunk_snapshot",
            notes="Legacy duplicated chunk snapshots that are not part of the active runtime contract.",
        ),
        item(
            "data/golden_set/",
            type="directory",
            category="candidate_for_project_repo",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="treat_as_project_evaluation_space",
            notes="Project-specific QA datasets used for the current baseline and accepted-manual gates.",
        ),
        item(
            "data/golden_set/QA_canonical.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_current_baseline_gate",
            notes="Current canonical baseline dataset used as a required operational gate.",
        ),
        item(
            "data/golden_set/QA_multihop.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_current_baseline_gate",
            notes="Current multihop baseline dataset used as a required operational gate.",
        ),
        item(
            "data/golden_set/QA_cross.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_current_baseline_gate",
            notes="Current cross-manual operational gate dataset.",
        ),
        item(
            "data/golden_set/QA_8070_quick_ref_bilingual_v2.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_current_project_gate",
            notes="Current quick-ref operational gate dataset for the accepted project scope.",
        ),
        item(
            "data/golden_set/QA_chunks_8070_installation_manual.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_manual_evaluation_dataset",
            notes="Installation manual evaluation dataset tied to the accepted project scope.",
        ),
        item(
            "data/golden_set/QA_chunks_man_8070_err.json",
            type="file",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_as_accepted_manual_evaluation_dataset",
            notes="Error-manual evaluation dataset tied to the accepted project scope.",
        ),
        item(
            "data/golden_set/QA_chunks_8070_operating_programming_manual.json",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_dataset",
            notes="Project-specific QA dataset for a manual not yet accepted into the runtime scope.",
        ),
        item(
            "data/golden_set/QA_chunks_8070_programming_manual.json",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_dataset",
            notes="Project-specific QA dataset for a manual not yet accepted into the runtime scope.",
        ),
        item(
            "data/golden_set/QA_chunks_8070_remote_modules.json",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_dataset",
            notes="Project-specific QA dataset for a manual not yet accepted into the runtime scope.",
        ),
        item(
            "data/golden_set/QA_chunks_manual_variables_cnc_8070.json",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_dataset",
            notes="Project-specific QA dataset for a manual not yet accepted into the runtime scope.",
        ),
        item(
            "data/golden_set/QA_chunks_dds_soft.json",
            type="file",
            category="candidate_for_project_repo",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="retain_as_future_project_onboarding_dataset",
            notes="Project-specific QA dataset for a manual not yet accepted into the runtime scope.",
        ),
        item(
            "data/processed/ontology_aligned.ttl",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="keep_as_runtime_tbox_contract",
            notes="Operational T-Box used by the live runtime and GraphDB publication.",
        ),
        item(
            "data/processed/abox_graphs/",
            type="directory",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_clean_runtime_path",
            notes="Current default operational chunk-level A-Box outputs for the base rebuild path.",
        ),
        item(
            "data/processed/abox_input.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Current default operational A-Box input artifact, rooted in the default density path.",
        ),
        item(
            "data/processed/abox_merged.ttl",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Merged operational raw A-Box snapshot used before canonicalization.",
        ),
        item(
            "data/processed/abox_canonical.ttl",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Canonicalized operational A-Box snapshot used before enrichment and link completion.",
        ),
        item(
            "data/processed/abox_enriched.ttl",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Enriched operational A-Box snapshot used before link completion.",
        ),
        item(
            "data/processed/abox_linked.ttl",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_and_publish_as_live_runtime_abox",
            notes="Live operational A-Box consumed by retrieval and GraphDB publication.",
        ),
        item(
            "data/processed/canonical_entity_map.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Canonical entity mapping produced by the live canonicalization stage.",
        ),
        item(
            "data/processed/canonicalization_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Canonicalization summary report for the active runtime build.",
        ),
        item(
            "data/processed/canonicalization_resolution_candidates.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Candidate merges and surface-variant resolutions considered by canonicalization.",
        ),
        item(
            "data/processed/enrichment_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Active enrichment report from the operational build chain.",
        ),
        item(
            "data/processed/enrichment_link_map.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Operational enrichment link map used for runtime traceability.",
        ),
        item(
            "data/processed/enrichment_surface_map.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Operational enrichment surface map used for runtime traceability.",
        ),
        item(
            "data/processed/link_completion_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Active link completion report from the operational build chain.",
        ),
        item(
            "data/processed/link_completion_map.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Operational link completion map used for runtime traceability.",
        ),
        item(
            "data/processed/link_completion_candidates.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Operational link completion candidates from the live build chain.",
        ),
        item(
            "data/processed/multilingual_lexicon.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="rebuild_from_operational_pipeline",
            notes="Active multilingual lexicon used by retrieval over the operational runtime.",
        ),
        item(
            "data/processed/graphdb_publication_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=True,
            project_specific=False,
            recommended_action="refresh_after_publication",
            notes="Publication trace of the live GraphDB mirror.",
        ),
        item(
            "data/processed/generalization_eval_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="refresh_as_baseline_gate",
            notes="Current canonical/generalization evaluation report used as a required baseline gate for this project.",
        ),
        item(
            "data/processed/multihop_eval_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="refresh_as_baseline_gate",
            notes="Current multihop evaluation report used as a required baseline gate for this project.",
        ),
        item(
            "data/processed/cross_eval_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="refresh_as_operational_gate",
            notes="Current cross-manual evaluation report used as an operational gate in the accepted project scope.",
        ),
        item(
            "data/processed/quick_ref_v2_eval_report.json",
            type="file",
            category="runtime_contract",
            runtime_critical=True,
            reusable=False,
            project_specific=True,
            recommended_action="refresh_as_operational_gate",
            notes="Current quick-ref V2 evaluation report used as an operational gate in the accepted project scope.",
        ),
        item(
            "data/processed/a218_*",
            type="artifact_group",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_and_rebuild_as_project_onboarding_state",
            notes="Accepted manual-specific artifacts for the A218 source manual, including density, input, manifest, chunk outputs, and merged graph.",
        ),
        item(
            "data/processed/quick_ref_*",
            type="artifact_group",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_and_rebuild_as_project_onboarding_state",
            notes="Accepted manual-specific artifacts for the 8070 quick-ref manual, including QA decisions and chunk outputs.",
        ),
        item(
            "data/processed/installation_manual_* and data/processed/8070_installation_*",
            type="artifact_group",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_and_rebuild_as_project_onboarding_state",
            notes="Accepted installation-manual artifacts, onboarding reports, evaluation outputs, and chunk directories tied to the current project scope.",
        ),
        item(
            "data/processed/man_8070_err_*",
            type="artifact_group",
            category="accepted_project_artifact",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_and_rebuild_as_project_onboarding_state",
            notes="Accepted error-manual artifacts, onboarding reports, evaluation outputs, and chunk directories tied to the current project scope.",
        ),
        item(
            "data/processed/t21_* through data/processed/t26_*",
            type="artifact_group",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=True,
            recommended_action="preserve_for_traceability_but_exclude_from_runtime_inputs",
            notes="Historical campaign outputs from earlier tasks; valuable as history, not as contract inputs for the runtime.",
        ),
        item(
            "data/processed/runtime_non_operational_inventory.json and data/processed/runtime_cleanup_second_pass_report.json",
            type="artifact_group",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_cleanup_history",
            notes="Repository cleanup and inventory reports from prior maintenance tasks; useful context but not runtime inputs.",
        ),
        item(
            "data/processed/runtime_clean_rebuild_preflight.json and data/processed/runtime_clean_rebuild_report.json",
            type="artifact_group",
            category="candidate_for_archive",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="retain_as_rebuild_traceability",
            notes="Reports specific to the clean rebuild campaign; not part of the stable runtime contract.",
        ),
        item(
            "data/processed/*debug*.json, data/processed/qa_failure_analysis.json, data/processed/query_debug_report.json, data/processed/synthesis_debug_report.json",
            type="artifact_group",
            category="debug_or_diagnostic",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="allow_refresh_or_overwrite_during_diagnostics",
            notes="Transient debug and diagnostic outputs that should remain visible but never be consumed as authoritative runtime inputs.",
        ),
        item(
            "data/processed/*_abox_debug/",
            type="artifact_group",
            category="debug_or_diagnostic",
            runtime_critical=False,
            reusable=False,
            project_specific=False,
            recommended_action="allow_refresh_or_archive_separately",
            notes="Chunk-level extraction debug directories used for troubleshooting provider and TTL issues.",
        ),
    ]

    deduped_paths = set()
    for entry in inventory:
        path = str(entry["path"])
        if path in deduped_paths:
            raise ValueError(f"Duplicate inventory path: {path}")
        deduped_paths.add(path)
    return sorted(inventory, key=lambda record: (str(record["category"]), str(record["path"])))


def main() -> None:
    inventory = build_inventory()
    counts = Counter(str(entry["category"]) for entry in inventory)
    payload = {
        "task": "T27A-001",
        "inventory_version": 1,
        "generated_from": "misc/coding-team/repo-reusability-core-split/generate_repo_inventory.py",
        "categories": sorted(ALLOWED_CATEGORIES),
        "item_count": len(inventory),
        "counts_by_category": dict(sorted(counts.items())),
        "items": inventory,
    }
    OUTPUT_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
